import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import Sidebar from '@/components/Sidebar/Sidebar'
import RecoilProvider from '@/providers/RecoilProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <RecoilProvider>
        <body className={inter.className}>
          {/* HEADER COMPONENT! */}
          <Header />

          <section className='flex h-[calc(100vh-52px)]'>
            {/* SIDEBAR! */}
            <Sidebar />

            {/* MAIN COMPONENT! */}
            <main className='grow'>{children}</main>
          </section>
        </body>
      </RecoilProvider>
    </html>
  )
}
