import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* HEADER COMPONENT! */}
        <Header />
        <section className="flex h-[calc(100vh-52px)]">
          {/* SIDEBAR! */}
          <aside className="w-[7vw] lg:w-[15vw] border-r-2 border-gray-200">
            sidebar
          </aside>
          {/* MAIN COMPONENT! */}
          <main className="grow">{children}</main>
        </section>
      </body>
    </html>
  );
}
