import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import Sidebar from '@/components/Sidebar/Sidebar'
import RecoilProvider from '@/providers/RecoilProvider'
import NextUIProvider from '@/providers/NextUIProvider'
import {StrictMode} from 'react';
import ToasterProvider from '@/providers/ToasterProvider'
import QueryProvider from '@/providers/QueryClientProvider'

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <RecoilProvider>
        <NextUIProvider>
          {/* MAIN BODY */}
          <body className={inter.className}>
          <ToasterProvider>
            <QueryProvider>
            <>

            {/* HEADER COMPONENT! */}
            <Header />

            <section className='flex h-[calc(100vh-52px)]'>
              {/* SIDEBAR! */}
              <Sidebar />

              {/* MAIN COMPONENT! */}
              <main className='grow'>{children}</main>
            </section>
            </>
            </QueryProvider>


          </ToasterProvider>

          </body>
        </NextUIProvider>
      </RecoilProvider>
    </html>
  )
}
